### ISSUE TITLE
Data augmentation methods

### ISSUE THREAD

**Issue by Djanghao** [mirzaim/VisionGNN#1]
Why not use Mixup and CutMix data augmentations in your implementation?

**Comment by mirzaim** [comment]
Hi,
Because of limited resources, we can train the models for 80 epochs.
To Mixup and CutMix be effective, We should train it more than 100 epochs.
I mention this problem in section 3.2 of the [report](https://github.com/mirzaim/VisionGNN/blob/main/docs/main.pdf).

**Comment by mirzaim** [comment]
``
